### PR TITLE
Update gpu.requirements.in

### PR DESCRIPTION
**Pull request by rgbkrk**
## Describe your changes

Include packages necessary for common models from huggingface 🤗 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I am able to build images locally
- [ ] Has the issue it resolves been discussed with maintainers?

### CODE REVIEW

**Comment by shouples** [comment]
I've overdue on writing up docks for these builds, but you'll need to run the task to resolve and lock these dependencies for to update the requirements.txt files used at build time here as well as updating the requirements.in file
https://github.com/noteable-io/kernels/blob/main/Taskfile.python.yaml#L271-L277

**Comment by rgbkrk** [comment]
Would that need to be run on a GPU instance so that it matches the actually determined dependencies?

**Comment by tizz98** [comment]
@rgbkrk you need to run `task datascience-gpu:lock-all-dependencies` locally

**Comment by rgbkrk** [comment]
Done. However, check out the changes in `gpu.requirements.txt` to see what I'm talking about:

```diff
diff --git a/python/datascience/3.10/gpu.requirements.txt b/python/datascience/3.10/gpu.requirements.txt
index 8bbc111..ded08ec 100644
--- a/python/datascience/3.10/gpu.requirements.txt
+++ b/python/datascience/3.10/gpu.requirements.txt
@@ -7,9 +7,11 @@
 absl-py==1.4.0
     # via
     #   tensorboard
-    #   tensorflow
+    #   tensorflow-macos
+accelerate==0.21.0
+    # via -r python/datascience/3.10/gpu.requirements.in
 astunparse==1.6.3
-    # via tensorflow
+    # via tensorflow-macos
 blis==0.7.9
     # via thinc
 cachetools==5.3.1
```

When packages are built (and in this case, just metadata generation before a build) they will be specific to the machine they were built on. At build time, it will check for the host OS as well as if GPU are available. This is one of the reasons that when running a model on our system there are warnings like this:

```
2023-08-07 12:54:35.154672: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-07 12:54:35.829796: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

**Comment by tizz98** [comment]
I see, we haven't had that issue before. Let me try running it on my linux computer

**Pull request merged**
